name: Update Tips Site Daily

on:
  schedule:
    - cron: '0 10 * * *'   # Runs daily at 11:00am UK time (BST = UTC+1)
  workflow_dispatch:

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pandas
        run: |
          pip install pandas

      - name: Run update script
        run: python update_tips.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto-update tips from CSV"
          git push
